version: '3.8'
services:
  trademaster-db:
    image: postgres:latest
    container_name: trademaster-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: TradeMasterDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
